# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-compositeproto
Summary:    X.Org X11 Protocol compositeproto
Version:    0.4.2
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/compositeproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-compositeproto.yaml
Provides:   compositeproto


%description
This package contains header files and documentation for the composite extension.



%prep
%setup -q -n compositeproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_includedir}/X11/extensions/composite.h
%{_includedir}/X11/extensions/compositeproto.h
%{_datadir}/pkgconfig/compositeproto.pc
%doc %{_datadir}/doc/compositeproto
# << files


